### ISSUE TITLE
REST API out of sync

### ISSUE THREAD

**Issue by bmeeder22** [rugglcon/SmartLock-server#6]
The REST API is not up to date for a couple of areas.
1. [Login](https://github.com/rugglcon/SmartLock-server/wiki/API-Documentation#login) and [Signup](https://github.com/rugglcon/SmartLock-server/wiki/API-Documentation#signup) return multiple locks on their success codes the new codes should be:
{
  "error": 0, 
  "data": {
    "user_id": [user_id], 
    "lock_id": [lock_id]
  }
}

2. The [/num_inside_users](https://github.com/rugglcon/SmartLock-server/wiki/API-Documentation#num_inside_users) needs to be supplied either a lock_id or user_id for that specific lock and will need to be changed to POST

**Comment by conruggles** [comment]
The returns for login and signup have been changed, and if the user does not have access to any locks the 'lock_id' will be -1. Also 'user_id' was added as a parameter to num_inside_users
